language: node_js
node_js:
    - "stable"
    - "4"
before_install:
    - echo "Installing latest stable npm version..."
    - npm install -g npm@latest
    - npm --version
before_script:
    - npm install -g gulp
script:
    - gulp test
